// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeImmTnAU_ooNhjtjbgJBf3ipDJZztNPk',
    appId: '1:892589536310:web:a2efd159eeb119aadfd497',
    messagingSenderId: '892589536310',
    projectId: 'demarco-todo',
    authDomain: 'demarco-todo.firebaseapp.com',
    storageBucket: 'demarco-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU70WYiR2HHKgmxM1TvaQCQn5QgDbPchw',
    appId: '1:892589536310:android:0a3cc5e2ae9d80cadfd497',
    messagingSenderId: '892589536310',
    projectId: 'demarco-todo',
    storageBucket: 'demarco-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dgaZLuECgY24BljNZrXc2ECS-5yKEeg',
    appId: '1:892589536310:ios:b61a3db11b8fe973dfd497',
    messagingSenderId: '892589536310',
    projectId: 'demarco-todo',
    storageBucket: 'demarco-todo.appspot.com',
    iosBundleId: 'com.example.demarcoTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dgaZLuECgY24BljNZrXc2ECS-5yKEeg',
    appId: '1:892589536310:ios:af7dda478d847370dfd497',
    messagingSenderId: '892589536310',
    projectId: 'demarco-todo',
    storageBucket: 'demarco-todo.appspot.com',
    iosBundleId: 'com.example.demarcoTodo.RunnerTests',
  );
}
